apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lightrag.fullname" . }}-config
  labels:
    {{- include "lightrag-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: lightrag
data:
  config.ini: |
{{ .Values.lightrag.config.configIniContent | nindent 4 }}