apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neo4j.fullname" . }}-secret
  labels:
    {{- include "lightrag-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: neo4j
type: Opaque
stringData:
  neo4jUsername: {{ .Values.neo4j.secret.neo4jUsername | quote }}
  neo4jPassword: {{ .Values.neo4j.secret.neo4jPassword | quote }}