apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    {{- include "lightrag-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lightrag-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: neo4j
  template:
    metadata:
      labels:
        {{- include "lightrag-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: neo4j
    spec:
      containers:
        - name: {{ .Values.neo4j.containerName }}
          image: "{{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag }}"
          imagePullPolicy: {{ .Values.neo4j.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.neo4j.ports.browser }}
              name: http
            - containerPort: {{ .Values.neo4j.ports.bolt }}
              name: bolt
          env:
            {{- range $key, $value := .Values.neo4j.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "neo4j.fullname" . }}-secret
          volumeMounts:
            - name: neo4j-plugins
              mountPath: /var/lib/neo4j/plugins
            - name: neo4j-import
              mountPath: /var/lib/neo4j/import
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-backups
              mountPath: /backups
      volumes:
        - name: neo4j-plugins
          emptyDir: {} # Plugins directory can be empty or a dedicated PVC if you need persistence for plugins
        - name: neo4j-import
          persistentVolumeClaim:
            claimName: {{ .Values.neo4j.persistence.import.name }}
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: {{ .Values.neo4j.persistence.data.name }}
        - name: neo4j-backups
          persistentVolumeClaim:
            claimName: {{ .Values.neo4j.persistence.backups.name }}