apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neo4j.fullname" . }}-secret
  labels:
    {{- include "lightrag-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: neo4j
type: Opaque
stringData:
  NEO4J_AUTH: {{ .Values.neo4j.secret.neo4jUsername}}/{{ .Values.neo4j.secret.neo4jPassword }}