apiVersion: v1
kind: Service
metadata:
  name: {{ include "lightrag.fullname" . }}
  labels:
    {{- include "lightrag-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: lightrag
spec:
  type: {{ .Values.lightrag.service.type }}
  ports:
    - port: {{ .Values.lightrag.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lightrag-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: lightrag